# Generated by Django 5.2.1 on 2025-05-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_review_name_review_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='promotions',
            field=models.ManyToManyField(blank=True, related_name='products', to='store.promotion'),
        ),
    ]
