# Generated by Django 5.2.1 on 2025-05-20 18:30

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_promotion_active_alter_product_promotions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.01000000000000000020816681711721685132943093776702880859375')), django.core.validators.MaxValueValidator(Decimal('0.9499999999999999555910790149937383830547332763671875'))]),
        ),
    ]
